[path_comment]
enabled = true

[path_comment.formats]
".go" = "/* $path$file */"
".html" = "<!-- $path$file -->"
".js" = "/* $path$file */"
".mjs" = "/* $path$file */"
".rs" = "/* $path$file */"
".ts" = "/* $path$file */"
".tsx" = "/* $path$file */"

[path_comment.exclude]
dirs = [".git", "node_modules", "target", "dist", ".seam", ".next", "generated", "pkg"]
patterns = []
