[package]
name = "seam-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Rust server core for the SeamJS compile-time rendering framework"
readme = "README.md"
keywords = ["seam", "ctr", "web", "axum", "template"]
categories = ["web-programming::http-server"]

[lints]
workspace = true

[dependencies]
axum = "0.8"
futures-core = "0.3"
seam-macros = { version = "0.2.12", path = "../rust-macros" }
serde = { version = "1", features = ["derive"] }
seam-injector = { version = "0.2.12", path = "../../injector/rust" }
serde_json = "1"
regex = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
