[project]
name = "client-react-example"

[build]
routes = "./src/routes.ts"
out_dir = ".seam/output"
bundler_command = "npx vite build"
bundler_manifest = ".seam/dist/.vite/manifest.json"
renderer = "react"
