[project]
name = "react-hono-tanstack"

[backend]
lang = "typescript"
dev_command = "bun --watch src/server/index.ts"
port = 3000

[frontend]
entry = "src/client/main.tsx"
dev_port = 5173

[build]
backend_build_command = "bun build src/server/index.ts --target=bun --outdir=.seam/output/server"
router_file = "src/server/router.ts"
routes = "./src/client/routes.ts"
out_dir = ".seam/output"
# typecheck_command = "bunx tsc --noEmit"
